tasks:
  - name: Terminal_1
    before: echo "Hello"
    command: |
      FROM gitpod/workspace-base

      USER gitpod

      # Install Homebrew
      RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc

      # Update Homebrew, Install Terraform & Azure CLI
      RUN eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && \
          brew update && \
          brew tap hashicorp/tap && \
          brew install hashicorp/tap/terraform && \
          brew upgrade terraform && \
          brew install azure-cli  && \
          brew install aztfexport
      
# vscode:
#   extensions:
#     - hashicorp.terraform
#     - ms-azuretools.vscode-azureresourcegroups
#     - formulahendry.code-runner