tasks:
  - name: install_azure_cli
    before: echo "Install Azure CLI"
    command: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
# vscode:
#   extensions:
#     - hashicorp.terraform
#     - ms-azuretools.vscode-azureresourcegroups
#     - formulahendry.code-runner